# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-08 22:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photo_app', '0002_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tag',
            name='collections',
            field=models.ManyToManyField(to='photo_app.Collection'),
        ),
    ]
