# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_level',
            field=models.IntegerField(default=0),
        ),
    ]
