# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20161116_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='office',
            field=models.CharField(default='', max_length=200),
        ),
    ]
